const typeActions = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_SIGNIN_SUCCESS: 'ADMIN_SIGNIN_SUCCESS',
    ADMIN_SIGNIN_FAIL: 'ADMIN_SIGNIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
    USER_EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
})

export default typeActions;